version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: diego
      POSTGRES_PASSWORD: diego1234
      POSTGRES_DB: bank_app
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # backend:
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
